name: inventory_falcons
description: "A new Flutter project."
environment:
  sdk: '^3.4.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
